http:
  routers:
    router-app-authors:
      entryPoints:
        - http
      service: service-app-authors
      #rule: Host(`authors.distribuida.com`)
      rule: PathPrefix(`/app-authors`)
    router-app-books:
      entryPoints:
        - http
      service: service-app-books
      #rule: Host(`authors.distribuida.com`)
      rule: PathPrefix(`/app-books`)
  services:
    service-app-authors:
      loadBalancer:
        servers:
          - url: 'http://localhost:9090'
          - url: 'http://localhost:9091'
    service-app-books:
      loadBalancer:
        servers:
          - url: 'http://localhost:8090'
          - url: 'http://localhost:8091'
  middlewares:
    mid-authors:
      stripPrefix:
        prefixes:
          - '/app-authors'
    mid-books:
      stripPrefix:
        prefixes:
          - '/app-books'